version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-9sb$-*w&x4zup&$p)#@r7$1rm)jtnd#_kxqhu!u+$m^74p%s&x
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379
#      - CELERY_BACKEND=redis://redis:6379
    links:
      - redis
    depends_on:
      - redis

  celery:
    build: ./
    command: celery -A image_pnev worker -l DEBUG
    volumes:
      - ./:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-9sb$-*w&x4zup&$p)#@r7$1rm)jtnd#_kxqhu!u+$m^74p%s&x
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#      - CELERY_BROKER=redis://redis:6379
#      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:6.0.8